### PR TITLE
fix index.html not loaded from its folder

### PR DESCRIPTION
**Pull request by Danfro**
With the current code index.html is NOT loaded from the apps `html` folder but from the `qml/html`folder. The later is .gitignored so not editable.

This is resulting the changes of your [commit](https://github.com/milikhin/seabass2/commit/8a5996e3d376867c2f48f0c2af1dd1b2b5dc00d1)  not being applied.

My PR is fixing this. index.html will now be loaded from the apps html folder. This folder will be installed by clickable into the apps structure.

### CODE REVIEW

**Comment by milikhin** [comment]
First of all, thank you for the pull requests!

How it works now: you need to run `npm run build` to apply changes in the `index.html` file.
As a part of a build script `index.html` will be copied from `html/` directory to `qml/html`.
At the same time JS files required for editor to work will be copied to the same `qml/html` directory.

Once application is started `index.html` is loaded into a webview.
Then `index.html` in turn requires `bundle.js` file from the same directory:
```
  - qml/
     |- html/
         |- index.html
         |- bundle.js <-- index.html loads this file
         |- ...other js files
```

For now the pull request won't work yet, because `index.html` won't be able to load `bundle.js` file:
```
  - html/
     |- index.html
     |- ... <-- no bundle.js file here!
  - qml/
     |- html/
         |- bundle.js <-- bundle.js file is still here!
         |- ...other js files
```

I really like the idea of not copying the index.html file to the qml/html directory as a build step.
We just need to move JS files from `qml/html` (it's definitely not the right place for the files, it was just easiest to implement for me :-) to something like `html/dist` and load `bundle.js` from there

**Comment by Danfro** [comment]
Just about to leave for work, but enough time for a small comment. ;-)

For UT my fix does the job. I tested that. 

Because this index.html is there **only** for UT as far as I can see. So if you need to change things for UT, just change the index.html in the `/ubports-sebass/html` folder. 
This is also more obvious for everyone looking at the code, because the `/ubports-sebass/qml/html/index.html` is listed in .gitignore, so a developer would think it not to be relevant.

What my changes are doing:
1. when running clickable, include the /html folder into the build click package.
2. change the source of the webview from `/ubports-sebass/qml/html/index.html` to `/ubports-sebass/html/index.html`.
The index.html in `/ubports-sebass/qml/html/` is actually not needed anymore after my changes.

The ../html is using a relative path like from main.qml go down one folder and look for html folder with index.html for source.

I hope this does make some sense. :smile:

**Comment by Danfro** [comment]
I already wondered if I need to run `npm run build` after you updated some code before I run clickable to actually include those changes.

I am sure there is a way to run commands from clickable as build precondition somehow. If that is the case, we should look into this. At least for the UT part.

**Comment by milikhin** [comment]
Thank you!

> For UT my fix does the job. I tested that.
It really shouldn't work yet as far as I understand :-). I've tested it too! :-)
The `index.html` will be loaded when starting the application, but opening files then won't work because of [this line](https://github.com/milikhin/seabass2/blob/master/ubports-seabass/html/index.html#L106).

Webview will look for `./bunlde.js` file relative to the loaded HTML file's directory and it just won't be there.

The pull request definitely makes things more obvious and I like really like that, just a few adjustments to webpack config are needed to make it work.

I'll look into it!

**Comment by Danfro** [comment]
Hm. You might have got me there. I think I did not try to open another file afterwards.

But I am sure clickable allows to include several ways to include "external" libaries like your js code on build time. So there should be a way to avoid manual copying. We may need to get help by someone deeper into this though.

**Comment by Danfro** [comment]
In your setup the html/index.html is not used at all. That was puzzeling me. Another attempt would be to copy this file to the qml/html folder. That was my first 'solution' but I did consider it bad coding style.

But if someone wants to propose changes to this file at least they would be picked up.

But that is me suggesting things you might have got in mind already. Use my ideas if they do help. Otherwise just ignore them. ☺

On Mon, 25 May 2020 21:38:44 -0700, Danfro wrote:
> Hm. You might have got me there. I think I did not try to open 
> another file afterwards.
>
> But I am sure clickable allows to include several ways to 
> include "external" libaries like your js code on build time. So 
> there should be a way to avoid manual copying. We may need to 
> get help by someone deeper into this though.
>

--

**Comment by Danfro** [comment]
Ok, with this commit at least it does open other files too. This will give us a working PR.
In theory the index.html file in `/qml/html` is now no longer needed.

**Comment by Danfro** [comment]
Alternatively, if I am missing another point, we could change the whole PR to my first solution by dropping changes to `index.html` and `main.qml`.

The new/added line in `cmakelist.txt` then needs to be changed to this:

` install(FILES html/index.html DESTINATION ${DATA_DIR}qml/html)`

This will copy `index.html` from the `html` folder to the `qml/html` folder when running clickable.

**Comment by milikhin** [comment]
Thank you!

I've merged your pull request and migrated all HTML assets to the `html/` directory, so there is no `qml/html` directory anymore: https://github.com/milikhin/seabass2/pull/20

**Pull request merged**
